namespace: wayfarer
enabled: true
image:
  tag: latest  # You can specify a different tag if needed
existingSecret: wayfarer-pgadmin-secret

service:
  type: ClusterIP            # Change to LoadBalancer for external access
  port: 80                   # Port for pgAdmin web access

# Persistent volume setup (optional)
persistence:
  enabled: false             # Disable persistence if not required
  size: 1Gi                  # Size of persistent volume if enabled
