image:
  repository: dashbh/wayfarer-auth
  tag: latest
  imagePullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 50051

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi